.PHONY: clean All

All:
	@echo "----------Building project:[ examen - Debug ]----------"
	@cd "examen" && "$(MAKE)" -f  "examen.mk"
clean:
	@echo "----------Cleaning project:[ examen - Debug ]----------"
	@cd "examen" && "$(MAKE)" -f  "examen.mk" clean
